name: music_concept_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0-beta+2

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  async: ^2.11.0
  audioplayers: ^5.1.0
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  equatable: ^2.0.5
  firebase_app_check: ^0.1.5+2
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_keyboard_visibility: ^5.4.1
  flutter_material_design_icons: ^1.1.7296
  flutter_native_splash: ^2.3.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_web_auth: ^0.5.0
  geolocator: ^9.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  google_maps_flutter: ^2.4.0
  image: ^4.0.15
  image_picker: ^0.8.7
  intl: ^0.18.1
  oauth2_client: ^3.0.0
  timeago: ^3.5.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/welcome/
    - assets/wallpapers/
    - assets/notification/
    - assets/logo/

  uses-material-design: true
